version: '3'

services:
  db-mms:
    image: mariadb:10.10.2
    container_name: db-mms
    restart: always
    # env_file:
    #   - 
    environment:
      MARIADB_DATABASE: ${MMS-MARIADB_DATABASE}
      MARIADB_USER: ${MMS-MARIADB_USER}
      MARIADB_PASSWORD: ${MMS-MARIADB_PASSWORD}
      MARIADB_ROOT_PASSWORD: ${MMS-MARIADB_ROOT_PASSWORD}
    volumes:
      - ../volumes/db/data:/var/lib/mysql
        # - /etc/mysql/my.cnf:/etc/mysql/my.cnf 
    #ports:
    #  - ${DB_PORT}:${DB_CONTAINER_PORT}
    expose:
      - ${MMS-DB_CONTAINER_PORT}
    networks:
      - mms-dev-net

  app-mms:
    image: mms:latest
    build:
      context: ../
      # args:
      #   - 
      dockerfile: ./deploy/app/Dockerfile
    container_name: app-mms
    restart: always
    # env_file:
    #   - 
    volumes:
      - ../:/srv/app/
    ports:
      - ${MMS_PORT}:6001
    expose:
      - 6001
    networks:
    - mms-dev-net

networks:
  mms-dev-net:
    driver: bridge
